BEGIN;
DROP TABLE IF EXISTS "animal",
"association",
"family",
"type",
"location",
"request",
"role";
CREATE TABLE "animal" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL,
  "gender" TEXT NOT NULL,
  "race" TEXT,
  "age" INTEGER NOT NULL,
  "size" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "url_image" TEXT UNIQUE,
  "availability" BOOLEAN NOT NULL,
  "family_id" INTEGER,
  "type_id" INTEGER NOT NULL,
  "association_id" INTEGER NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "association" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL,
  "email" TEXT UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "adress" TEXT NOT NULL,
  "phone_number" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "url_image" TEXT UNIQUE,
  "role_id" INTEGER NOT NULL,
  "location_id" INTEGER NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "family" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "firstname" TEXT NOT NULL,
  "lastname" TEXT NOT NULL,
  "email" TEXT UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "adress" TEXT NOT NULL,
  "phone_number" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "url_image" TEXT UNIQUE,
  "role_id" INTEGER NOT NULL,
  "location_id" INTEGER NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "type" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "location" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "department_number" INTEGER NOT NULL,
  "department_name" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "request" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "status" TEXT NOT NULL,
  "family_id" INTEGER NOT NULL,
  "animal_id" INTEGER NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "role" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "family"
ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");
ALTER TABLE "family"
ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id");
ALTER TABLE "animal"
ADD FOREIGN KEY ("family_id") REFERENCES "family" ("id");
ALTER TABLE "animal"
ADD FOREIGN KEY ("type_id") REFERENCES "type" ("id");
ALTER TABLE "association"
ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");
ALTER TABLE "association"
ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id");
ALTER TABLE "animal"
ADD FOREIGN KEY ("association_id") REFERENCES "association" ("id");
ALTER TABLE "request"
ADD FOREIGN KEY ("family_id") REFERENCES "family" ("id");
ALTER TABLE "request"
ADD FOREIGN KEY ("animal_id") REFERENCES "animal" ("id");
COMMIT;